name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Python
      run:  sudo apt -y install python
    - name: Install pytest
      run:  sudo apt install pylint
    - name: Change folder
      run:  cd 3_implementation

